<?php

namespace app\models;

use webvimark\modules\UserManagement\models\User as UserBase;
use yii\helpers\ArrayHelper;

class User extends UserBase
{
    public static $user;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        self::$user = self::findIdentity($token->getClaim('uid'));
        return new static(self::$user);
    }

    public function getWriter()
    {
        return $this->hasOne(Writer::class, ['user_id' => 'id']);
    }

    static function getList()
    {
        return ArrayHelper::map(self::find()->asArray()->all(), 'id', 'username');
    }
}
